# Describes the format for available canada_post services

add_tracking:
  description: Add new tracking number
  fields:
    tracking_number:
      description: Tracking number
      example: "123456789"
    title:
      description: Custom title
      example: "Sit Stand Desk"